# Generated by Django 4.2.22 on 2026-05-15 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('hours_spent', models.FloatField(default=0)),
                ('tags', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('mentor', 'Mentor')], default='member', max_length=10)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(blank=True, default='#3a6b4d', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='logs.log')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
